server:
  port: 8888

spring:
  datasource:
    #  url: jdbc:h2:tcp://localhost/~/querydsl
    #url: jdbc:h2:mem:testdb
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  jdbc:
    sqlonly: off
    sqltiming: info
    resultsettable: info
    audit: off
    resultset: off
    connection: off
  org.hibernate:
    SQL: debug
#  org.hibernate.type: trace
