server:
  port: 8888

spring:
  datasource:
    #  url: jdbc:h2:tcp://localhost/~/querydsl
    #url: jdbc:h2:mem:testdb
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  jdbc:
    sqlonly: info
    sqltiming: off
    resultsettable: off #info
    audit: off
    resultset: off #info
    connection: off
  org.hibernate:
    SQL: OFF #debug
#  org.hibernate.type: trace
